# Efficient Frontiner from Modern Portfolio Theory implemented in Python

## Modern Portfolio Theory

In [2]:
import pandas as pd  
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf
import scipy.optimize as sco
from Get_Stocks import*
from EF import PortfolioOptimization
plt.style.use('fivethirtyeight')
np.random.seed(777)

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [18]:
# #Efectuamos los inputs de los parametros que las funciones van a recibir

# n_cotizacion = int(input("Ingrese el número de años de cotización a filtrar: "))
# precio_max = int(input("Ingrese el precio máximo por el cual quiere filtrar: "))
# precio_min = int(input("Ingrese el precio mínimo por el cual quiere filtrar: "))
# beta_max = float(input("Ingrese el beta máximo por el cual quiere filtrar: "))

In [19]:

# stock_filter = StockFilter()

# # Call the methods on the instance
# data = down_stocks()
# # data = stock_filter.filtro_betas(data,'betas_file.csv',beta_max)
# data = stock_filter.filtro_nulo(data)
# data = stock_filter.filtro_tiempo(data,n_cotizacion)
# data = stock_filter.filtro_precio(data,precio_max, precio_min)

# table = data

In [3]:

stocks = ['AAPL', 'GOOGL', 'MSFT', 'AMZN', 'META', 'TSLA', 'NVDA', 'JPM', 'V', 'JNJ', 'BABA', 'WMT', 'PG', 'MA', 'UNH', 'DIS', 'HD', 'PYPL', 'CMCSA', 'VZ', 'ADBE', 'NFLX', 'INTC', 'PFE', 'CRM', 'BAC', 'T', 'ABBV', 'XOM', 'KO', 'CVX', 'CSCO', 'PEP', 'TMO', 'NKE', 'MRK', 'ABT', 'WFC', 'WBA', 'ORCL', 'AMGN', 'MCD', 'MDT', 'HON', 'IBM', 'COST', 'TXN', 'MMM', 'ACN', 'BA', 'LLY']

data = yf.download(stocks, start = '2010-01-01')['Adj Close']
table = data

[*********************100%***********************]  51 of 51 completed

In [21]:
table

,AAPL,ABBV,ABT,ACN,ADBE,AMGN,AMZN,BA,BABA,BAC,...,TMO,TSLA,TXN,UNH,V,VZ,WBA,WFC,WMT,XOM
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,6.496294,NaN,19.336395,32.708153,37.090000,42.488071,6.695000,43.777542,NaN,12.977034,...,45.326931,NaN,18.492167,25.785116,20.016436,16.298611,25.593067,19.222214,40.013050,41.319069
2010-01-05,6.507524,NaN,19.180180,32.910301,37.700001,42.120022,6.734500,45.211357,NaN,13.398850,...,45.479603,NaN,18.385523,25.744226,19.787069,16.327993,25.387228,19.749908,39.614616,41.480392
2010-01-06,6.404014,NaN,19.286695,33.260159,37.619999,41.803501,6.612500,46.582798,NaN,13.555999,...,45.909046,NaN,18.250439,25.997744,19.521357,15.858499,25.195110,19.778055,39.526081,41.838909
2010-01-07,6.392176,NaN,19.446470,33.229065,36.889999,41.420719,6.500000,48.468571,NaN,14.002628,...,45.909046,NaN,18.307310,26.995451,19.703047,15.764101,25.346048,20.495722,39.548229,41.707455
2010-01-08,6.434672,NaN,19.545891,33.096886,36.689999,41.788761,6.676000,48.001011,NaN,13.878562,...,46.681980,NaN,18.726784,26.741932,19.757542,15.774046,25.380358,20.305752,39.349007,41.540154
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-12,183.789993,137.729996,101.400002,311.480011,474.630005,217.360001,126.570000,221.559998,85.860001,29.129999,...,523.341614,249.830002,174.039993,490.576172,226.169998,35.610001,31.639999,41.830002,154.100006,106.419998
2023-06-13,183.309998,138.309998,101.860001,315.160004,478.989990,221.990005,126.660004,220.380005,87.510002,29.400000,...,525.700012,258.709991,177.410004,489.301422,223.399994,35.480000,31.950001,42.650002,155.300003,106.440002
2023-06-14,183.949997,136.229996,103.250000,315.049988,479.529999,222.279999,126.419998,216.899994,89.360001,29.120001,...,520.119995,256.790009,177.119995,457.979980,223.440002,35.730000,31.510000,42.080002,156.869995,105.160004
2023-06-15,186.009995,135.889999,105.019997,323.769989,490.910004,228.440002,127.110001,219.410004,92.199997,29.370001,...,535.109985,255.899994,178.089996,465.890015,226.169998,36.439999,32.020000,42.360001,157.729996,105.889999
2023-06-16,184.919998,138.639999,106.199997,319.540009,495.179993,229.660004,125.489998,219.990005,92.099998,29.190001,...,537.299988,260.540009,176.759995,458.489990,228.910004,36.459999,32.669998,42.180000,155.529999,105.129997

In [22]:
# symbols = list(table.head(0))
noa = len(stocks)
# symbols[:]

In [4]:
# Assuming you have the necessary inputs:
log_returns = np.log(table / table.shift(1))
mean_returns = log_returns.mean()
cov_matrix = log_returns.cov()
num_portfolios = 25000
risk_free_rate = 0.0178

# Create an instance of the PortfolioOptimization class
portfolio = PortfolioOptimization(table)

# Call the methods of the class using the instance
portfolio.display_calculated_ef_with_random(mean_returns, cov_matrix, num_portfolios, risk_free_rate)

--------------------------------------------------------------------------------
Maximum Sharpe Ratio Portfolio Allocation

Annualised Return: 0.23
Annualised Volatility: 0.18


             AAPL   COST    HD    LLY   MCD  NFLX  NVDA  TSLA    UNH
allocation  10.59  20.35  2.56  30.14  8.32  4.35  4.65  7.68  11.36
--------------------------------------------------------------------------------
Minimum Volatility Portfolio Allocation

Annualised Return: 0.1
Annualised Volatility: 0.13


            ABBV  BABA  COST   JNJ    KO  LLY   MCD  MRK  NFLX   PEP   PFE  \
allocation  0.03  2.77  2.82  16.2  9.93  1.4  14.4  2.8  0.45  0.99  3.45

              PG     T     VZ    WMT   XOM
allocation  9.94  0.04  19.31  15.13  0.33