In [1]:
import pandas as pd  
import numpy as np
import yfinance as yf
import collections

from Get_Stocks import StockFilter, StockFilterParticular, down_stocks

In [2]:
stock_filter = StockFilter()
stock_filter_particular = StockFilterParticular()

# Call the methods on the instance
data = down_stocks()
data = stock_filter.filtro_nulo(data)
data, sharpe_ratios = stock_filter.filtro_sharpe(data)
data = stock_filter_particular.filtro_sector(data, sharpe_ratios)

[*********************100%***********************]  503 of 503 completed

2 Failed downloads:
- BRK.B: No timezone found, symbol may be delisted
- BF.B: No data found for this date range, symbol may be delisted

In [3]:
data

,A,AAPL,ABBV,ABC,ABT,ACGL,ACN,ADBE,ADI,ADM,...,WRB,WST,WTW,WY,XEL,XOM,XYL,YUM,ZBH,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-02,37.823856,24.531761,46.113224,79.136971,38.241337,19.496668,77.119682,72.339996,46.285801,41.013771,...,19.059296,50.073761,103.250443,25.309975,28.097229,63.172096,34.136860,44.306362,102.393486,40.864922
2015-01-05,37.115131,23.840668,45.245426,78.463356,38.249855,19.379999,75.817566,71.980003,45.444084,39.594624,...,18.889965,49.382545,102.508835,25.309975,27.778299,61.443573,32.012272,43.406155,106.213097,40.619595
2015-01-06,36.536953,23.842911,45.021465,78.892029,37.815491,19.423332,75.270676,70.529999,44.377357,38.814079,...,18.841049,48.537739,101.998947,25.281948,27.926096,61.116932,31.824028,42.873383,105.312790,40.223312
2015-01-07,37.021873,24.177242,46.841095,80.466721,38.122108,19.536667,76.850571,71.110001,44.844048,39.397507,...,18.859865,49.324955,103.459053,25.359051,28.167236,61.736198,32.075020,44.294117,107.931946,41.053631
2015-01-08,38.131580,25.106180,47.330982,80.650414,38.905663,19.876667,78.022491,72.919998,45.635765,38.821964,...,19.262493,50.294552,104.641014,25.632395,28.493954,62.763771,32.317070,45.065727,109.077835,41.685810
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-05-31,115.669998,177.250000,137.960007,170.149994,102.000000,69.699997,305.920013,417.790009,176.842972,70.650002,...,55.680000,334.630005,218.850006,28.469999,65.290001,102.180000,100.199997,128.690002,127.339996,163.009995
2023-06-01,116.260002,180.089996,133.440002,172.589996,102.820000,69.669998,305.200012,426.750000,179.550003,70.550003,...,56.910000,341.529999,220.220001,28.540001,63.549999,103.360001,102.129997,132.250000,127.360001,166.000000
2023-06-02,118.220001,180.949997,136.869995,174.520004,104.199997,70.900002,311.390015,436.369995,179.800003,71.970001,...,57.650002,343.730011,224.529999,28.830000,63.139999,105.760002,105.059998,134.529999,129.809998,171.880005
2023-06-05,118.349998,179.580002,136.860001,174.690002,103.760002,71.300003,304.450012,434.179993,174.979996,71.269997,...,57.419998,343.399994,223.669998,28.360001,63.950001,105.290001,106.160004,134.169998,130.470001,171.119995
2023-06-06,117.440002,179.210007,135.429993,174.369995,102.620003,71.199997,308.040009,432.890015,177.970001,72.389999,...,57.549999,346.190002,224.229996,28.940001,63.560001,106.150002,106.290001,132.880005,130.270004,170.139999